import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://bbktjircoangqvusirap.supabase.co';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJia3RqaXJjb2FuZ3F2dXNpcmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI0NDI3NzQsImV4cCI6MjA5ODAxODc3NH0.RIy_uePmskvjkwK2hMHIFVZey1h3MmB2fIMR8nZtXec';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

console.log('[Supabase] Client initialized with URL:', supabaseUrl);

export type DbTables = {
  organizations: {
    id: string;
    name: string;
    type: 'school' | 'gymnasium' | 'college' | 'lyceum';
    city: string | null;
    address: string | null;
    created_at: string;
    updated_at: string;
  };
  profiles: {
    id: string;
    email: string;
    display_name: string;
    first_name: string | null;
    role: 'admin' | 'deputy' | 'teacher' | 'methodologist' | 'accountant';
    is_active: boolean;
    organization_id: string | null;
    teacher_id: string | null;
    permissions: string[];
    allowed_pages: string[];
    created_at: string;
    updated_at: string;
  };
  teachers: {
    id: string;
    organization_id: string;
    name: string;
    subject_ids: string[];
    shifts: string[];
    max_periods: number;
    class_teacher_of: string | null;
    unavailable_dates: string[];
    absence_reasons: Record<string, string>;
    birth_date: string | null;
    telegram_chat_id: string | null;
    order: number | null;
    created_at: string;
    updated_at: string;
  };
  classes: {
    id: string;
    organization_id: string;
    name: string;
    shift: string;
    students_count: number;
    grade: string | null;
    class_teacher_id: string | null;
    exclude_from_reports: boolean;
    order: number | null;
    created_at: string;
    updated_at: string;
  };
  subjects: {
    id: string;
    organization_id: string;
    name: string;
    color: string | null;
    difficulty: number | null;
    required_room_type: string | null;
    order: number | null;
    created_at: string;
    updated_at: string;
  };
  rooms: {
    id: string;
    organization_id: string;
    name: string;
    floor: number | null;
    capacity: number | null;
    type: string | null;
    order: number | null;
    created_at: string;
    updated_at: string;
  };
  settings: {
    id: string;
    organization_id: string;
    school_year: string | null;
    semester_start_1: string | null;
    semester_end_1: string | null;
    semester_start_2: string | null;
    semester_end_2: string | null;
    shift1_start: string | null;
    shift1_end: string | null;
    shift2_start: string | null;
    shift2_end: string | null;
    periods: number;
    shift1_periods: number;
    shift2_periods: number;
    max_periods: number;
    telegram_token: string | null;
    public_schedule_id: string | null;
    feedback_chat_id: string | null;
    admin_telegram_chat_id: string | null;
    bell_presets: unknown | null;
    semester_config: unknown | null;
    telegram_templates: unknown | null;
    admin_announcement: unknown | null;
    substitution_day_comments: unknown | null;
    weather_api_key: string | null;
    weather_city: string | null;
    dashboard_widget_access: unknown | null;
    is_schedule_locked: boolean | null;
    allow_teacher_edit: boolean | null;
    auto_backup: boolean | null;
    backup_time: string | null;
    current_year: number | null;
    director_name: string | null;
    school_name: string | null;
    secretary_name: string | null;
    union_chair_name: string | null;
    telegram_bot_name: string | null;
    google_apps_script_url: string | null;
    created_at: string;
    updated_at: string;
  };
  schedule_items: {
    id: string;
    organization_id: string;
    semester: number;
    day: 'Пн' | 'Вт' | 'Ср' | 'Чт' | 'Пт';
    period: number;
    shift: string;
    class_id: string | null;
    subject_id: string | null;
    teacher_id: string | null;
    room_id: string | null;
    direction: string | null;
    created_at: string;
    updated_at: string;
  };
  substitutions: {
    id: string;
    organization_id: string;
    date: string;
    schedule_item_id: string | null;
    original_teacher_id: string | null;
    replacement_teacher_id: string | null;
    replacement_room_id: string | null;
    replacement_class_id: string | null;
    replacement_subject_id: string | null;
    is_merger: boolean;
    lesson_absence_reason: string | null;
    refusals: string[];
    comment: string | null;
    day_comment: string | null;
    is_read: boolean;
    created_at: string;
    updated_at: string;
  };
  absenteeism: {
    id: string;
    organization_id: string;
    date: string;
    class_id: string | null;
    absences: unknown[];
    present_count: number;
    absent_count: number;
    entered_by: string | null;
    entered_at: string | null;
    updated_at: string | null;
    updated_by: string | null;
    created_at: string;
  };
  nutrition: {
    id: string;
    organization_id: string;
    date: string;
    class_id: string | null;
    breakfast_count: number;
    lunch_count: number;
    dinner_count: number;
    total_count: number;
    benefit_count: number;
    regular_count: number;
    entered_by: string | null;
    entered_at: string | null;
    created_at: string;
    updated_at: string;
  };
  duty: {
    id: string;
    organization_id: string;
    day: string;
    shift: string;
    zone_id: string | null;
    teacher_id: string | null;
    created_at: string;
    updated_at: string;
  };
  audit_log: {
    id: string;
    organization_id: string;
    user_id: string | null;
    user_email: string | null;
    action: string;
    collection: string | null;
    target_id: string | null;
    details: Record<string, unknown> | null;
    created_at: string;
  };
  bell_schedule: {
    id: string;
    organization_id: string;
    period: number;
    start_time: string;
    end_time: string;
    shift: string | null;
    day: string;
    cancelled: boolean;
    created_at: string;
  };
};
